# Generated by Django 4.1.7 on 2023-03-05 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
                ('tags', models.CharField(help_text='comma-separated list of tags', max_length=4096)),
                ('url', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=4096)),
                ('type', models.CharField(max_length=100)),
                ('possible_answers', models.CharField(blank=True, max_length=4096, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchtime', models.FloatField(blank=True, default=0.0, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('years_of_experience', models.FloatField(default=0.0)),
                ('role', models.CharField(blank=True, max_length=4096, null=True)),
                ('skill_interests', models.TextField(blank=True, max_length=4096, null=True)),
                ('other_interests', models.TextField(blank=True, max_length=4096, null=True)),
                ('planner_score', models.FloatField(default=0.0)),
                ('guardian_score', models.FloatField(default=0.0)),
                ('mentor_score', models.FloatField(default=0.0)),
                ('motivator_score', models.FloatField(default=0.0)),
                ('assessor_score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, max_length=4096, null=True)),
                ('human_approved', models.BooleanField(default=False)),
                ('human_edited', models.BooleanField(default=False)),
                ('feedback_edit_history', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerToVideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=4096)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.videoquestion')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.video')),
            ],
        ),
    ]
