# Generated by Django 4.1.7 on 2023-03-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_module_modulecompletion_delete_videocompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnermodel',
            name='school_level',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
