# Generated by Django 4.1.7 on 2023-03-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_answertovideoquestion_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendationqueue',
            old_name='list_of_video_ids',
            new_name='list_of_module_ids',
        ),
    ]
