# Generated by Django 4.1.7 on 2023-03-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_learnermodel_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
                ('list_of_module_ids', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='module',
            name='feedback_rating',
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='feedback',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='modulecompletion',
            name='feedback_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='videoquestion',
            name='possible_answers',
            field=models.CharField(blank=True, help_text='Please leave blank if OEQ', max_length=4096, null=True),
        ),
    ]
