# Generated by Django 4.1.7 on 2023-03-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_track_remove_module_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='list_of_module_ids',
        ),
        migrations.AddField(
            model_name='video',
            name='series_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
                ('track_order', models.IntegerField(blank=True, default=0, null=True)),
                ('primary_level', models.BooleanField(default=False)),
                ('secondary_level', models.BooleanField(default=False)),
                ('admin_level', models.BooleanField(default=False)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.track')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.series'),
        ),
    ]
