# Generated by Django 4.1.7 on 2023-03-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnermodel',
            name='current_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.feedback'),
        ),
    ]
