# Generated by Django 4.1.7 on 2023-03-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_learnermodel_current_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendationqueue',
            old_name='list_of_module_ids',
            new_name='list_of_ids',
        ),
    ]
