# Generated by Django 4.1.7 on 2023-03-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_list_of_module_ids_recommendationqueue_list_of_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnermodel',
            name='cluster',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
