# Generated by Django 4.1.7 on 2023-03-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_learnermodel_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnermodel',
            name='series_completed',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
