# Generated by Django 4.1.7 on 2023-05-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_feedback_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_feedback',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
