# Generated by Django 4.1.7 on 2023-06-16 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_feedback_user_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('series_order',)},
        ),
    ]
